export async function exportChartAsPNG(element: HTMLElement, filename: string): Promise<void> {
  const { default: html2canvas } = await import("html2canvas");
  const canvas = await html2canvas(element, {
    backgroundColor: "#ffffff",
    scale: 2,
    useCORS: true,
    logging: false,
  });
  const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/png"));
  if (!blob) return;
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${filename.replace(/[^a-z0-9]/gi, "_")}.png`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function exportChartAsSVG(element: HTMLElement, filename: string): Promise<void> {
  const { default: html2canvas } = await import("html2canvas");
  const canvas = await html2canvas(element, {
    backgroundColor: "#ffffff",
    scale: 2,
    useCORS: true,
    logging: false,
  });
  const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/png"));
  if (!blob) return;
  // Convert canvas to SVG-compatible format
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${filename.replace(/[^a-z0-9]/gi, "_")}.svg`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function exportDataAsExcel(data: Record<string, any>[], filename: string): Promise<void> {
  try {
    const { default: XLSX } = await import("xlsx");
    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Data");
    XLSX.writeFile(workbook, `${filename.replace(/[^a-z0-9]/gi, "_")}.xlsx`);
  } catch (error) {
    console.error("Excel export failed:", error);
  }
}

export async function exportDashboardAsPDF(title: string, sectionElements: (HTMLElement | null)[]): Promise<void> {
  const { default: html2canvas } = await import("html2canvas");
  const { default: jsPDF } = await import("jspdf");

  const pdf = new jsPDF({ orientation: "portrait", unit: "px", format: "a4" });
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 32;
  let y = margin;

  // Title
  pdf.setFontSize(20);
  pdf.setTextColor(77, 116, 100); // sage dark
  pdf.text(title, margin, y);
  y += 28;

  pdf.setFontSize(10);
  pdf.setTextColor(99, 110, 114);
  pdf.text(`Generated by synQ · ${new Date().toLocaleString()}`, margin, y);
  y += 24;

  const sections = sectionElements.filter(Boolean) as HTMLElement[];

  for (const el of sections) {
    const canvas = await html2canvas(el, { backgroundColor: "#ffffff", scale: 1.5, useCORS: true, logging: false });
    const imgData = canvas.toDataURL("image/png");
    const ratio = canvas.width / canvas.height;
    const imgW = pageW - margin * 2;
    const imgH = imgW / ratio;

    if (y + imgH > pageH - margin) {
      pdf.addPage();
      y = margin;
    }

    pdf.addImage(imgData, "PNG", margin, y, imgW, imgH);
    y += imgH + 16;
  }

  pdf.save(`${title.replace(/[^a-z0-9]/gi, "_")}_synQ.pdf`);
}
