"use client";

import { X, Download, BookOpen, Lightbulb, AlertTriangle, TrendingUp, Star } from "lucide-react";
import type { DataStory } from "@/types";

interface StoryCardProps {
  story: DataStory;
  onClose: () => void;
}

function Section({
  icon, title, color, children,
}: { icon: React.ReactNode; title: string; color: string; children: React.ReactNode }) {
  return (
    <div className="mb-5">
      <div className="flex items-center gap-2 mb-2">
        <span style={{ color }}>{icon}</span>
        <h3 className="text-xs font-bold uppercase tracking-widest" style={{ color }}>
          {title}
        </h3>
      </div>
      {children}
    </div>
  );
}

function downloadStory(story: DataStory) {
  const lines = [
    `${story.title}`,
    `${"=".repeat(story.title.length)}`,
    "",
    "EXECUTIVE SUMMARY",
    story.executive_summary,
    "",
    "KEY FINDINGS",
    ...story.key_findings.map((f, i) => `${i + 1}. ${f}`),
    "",
    "ANOMALIES & RISKS",
    ...(story.anomalies.length > 0 ? story.anomalies.map((a) => `• ${a}`) : ["None identified"]),
    "",
    "RECOMMENDATIONS",
    ...story.recommendations.map((r, i) => `${i + 1}. ${r}`),
    "",
    "CONCLUSION",
    story.conclusion,
    "",
    `Generated by synQ — ${new Date().toLocaleString()}`,
  ];
  const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = Object.assign(document.createElement("a"), { href: url, download: "data-story.txt" });
  a.click();
  URL.revokeObjectURL(url);
}

export function StoryCard({ story, onClose }: StoryCardProps) {
  return (
    <div
      className="rounded-2xl overflow-hidden"
      style={{
        background: "linear-gradient(135deg, rgba(30, 28, 26,0.06) 0%, rgba(255,255,255,0.95) 100%)",
        border: "1px solid rgba(30, 28, 26,0.25)",
        boxShadow: "0 8px 32px rgba(30, 28, 26,0.12), 0 2px 8px rgba(0,0,0,0.06)",
        animation: "fade-in-scale 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
      }}
    >
      {/* Header */}
      <div
        className="flex items-start justify-between px-5 py-4"
        style={{
          background: "linear-gradient(120deg, rgba(30, 28, 26,0.12) 0%, rgba(30, 28, 26,0.04) 100%)",
          borderBottom: "1px solid rgba(30, 28, 26,0.15)",
        }}
      >
        <div className="flex items-center gap-3">
          <div
            className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0"
            style={{ background: "rgba(30, 28, 26,0.15)" }}
          >
            <BookOpen className="w-5 h-5" style={{ color: "var(--color-sage)" }} />
          </div>
          <div>
            <div className="flex items-center gap-2 mb-0.5">
              <span
                className="text-[10px] font-bold uppercase tracking-widest px-2 py-0.5 rounded-full"
                style={{ background: "rgba(30, 28, 26,0.15)", color: "var(--color-sage)" }}
              >
                AI Data Story
              </span>
            </div>
            <h2 className="text-base font-bold leading-tight" style={{ color: "var(--color-sage-dark)" }}>
              {story.title}
            </h2>
          </div>
        </div>
        <div className="flex items-center gap-1 flex-shrink-0 ml-3">
          <button
            onClick={() => downloadStory(story)}
            title="Download as TXT"
            className="p-2 rounded-xl transition-all duration-150 cursor-pointer"
            style={{ color: "var(--color-text-muted)" }}
            onMouseEnter={(e) => { e.currentTarget.style.background = "rgba(30, 28, 26,0.1)"; e.currentTarget.style.color = "var(--color-sage)"; }}
            onMouseLeave={(e) => { e.currentTarget.style.background = "transparent"; e.currentTarget.style.color = "var(--color-text-muted)"; }}
          >
            <Download className="w-4 h-4" />
          </button>
          <button
            onClick={onClose}
            title="Dismiss"
            className="p-2 rounded-xl transition-all duration-150 cursor-pointer"
            style={{ color: "var(--color-text-muted)" }}
            onMouseEnter={(e) => { e.currentTarget.style.background = "rgba(214,48,49,0.08)"; e.currentTarget.style.color = "#d63031"; }}
            onMouseLeave={(e) => { e.currentTarget.style.background = "transparent"; e.currentTarget.style.color = "var(--color-text-muted)"; }}
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Body */}
      <div className="px-5 py-4">
        {/* Executive Summary */}
        <div
          className="mb-5 p-3.5 rounded-xl text-sm leading-relaxed"
          style={{
            background: "rgba(30, 28, 26,0.06)",
            border: "1px solid rgba(30, 28, 26,0.12)",
            color: "var(--color-text-primary)",
          }}
        >
          {story.executive_summary}
        </div>

        {/* Key Findings */}
        <Section icon={<Star className="w-3.5 h-3.5" />} title="Key Findings" color="var(--color-sage)">
          <ol className="flex flex-col gap-2">
            {story.key_findings.map((f, i) => (
              <li key={i} className="flex items-baseline gap-2.5">
                <span
                  className="w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold flex-shrink-0"
                  style={{ background: "rgba(30, 28, 26,0.12)", color: "var(--color-sage)" }}
                >
                  {i + 1}
                </span>
                <span className="text-sm leading-relaxed" style={{ color: "var(--color-text-primary)" }}>{f}</span>
              </li>
            ))}
          </ol>
        </Section>

        {/* Anomalies */}
        {story.anomalies.length > 0 && (
          <Section icon={<AlertTriangle className="w-3.5 h-3.5" />} title="Anomalies & Risks" color="#d97706">
            <ul className="flex flex-col gap-2">
              {story.anomalies.map((a, i) => (
                <li key={i} className="flex items-baseline gap-2.5">
                  <span className="w-1.5 h-1.5 rounded-full flex-shrink-0 mt-2" style={{ background: "#f59e0b" }} />
                  <span className="text-sm leading-relaxed" style={{ color: "var(--color-text-primary)" }}>{a}</span>
                </li>
              ))}
            </ul>
          </Section>
        )}

        {/* Recommendations */}
        <Section icon={<Lightbulb className="w-3.5 h-3.5" />} title="Recommendations" color="var(--color-sage)">
          <ol className="flex flex-col gap-2">
            {story.recommendations.map((r, i) => (
              <li key={i} className="flex items-baseline gap-2.5">
                <span
                  className="w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold flex-shrink-0"
                  style={{ background: "rgba(30, 28, 26, 0.10)", color: "var(--color-sage)" }}
                >
                  {i + 1}
                </span>
                <span className="text-sm leading-relaxed" style={{ color: "var(--color-text-primary)" }}>{r}</span>
              </li>
            ))}
          </ol>
        </Section>

        {/* Conclusion */}
        <Section icon={<TrendingUp className="w-3.5 h-3.5" />} title="Conclusion" color="var(--color-sage-dark)">
          <p
            className="text-sm leading-relaxed italic"
            style={{
              color: "var(--color-text-primary)",
              borderLeft: "3px solid var(--color-sage)",
              paddingLeft: "12px",
            }}
          >
            {story.conclusion}
          </p>
        </Section>
      </div>
    </div>
  );
}
